pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                node ('ubuntu') {
                    sh ("echo Hello World");
                    dir ("/home/omar/Eng/Courses/DEPI/Technical/Lec5/depi/docker/mongo-compose") {
                        sh ("docker compose up -d")
                    }
                }
            }
        }
    }
}

